### ISSUE TITLE
Plugin is not working with webpack cache

### ISSUE THREAD

**Issue by artem-malko** [pinojs/pino-webpack-plugin#3]
Hi! Thx for the plugin, it helps a lot to use pino with typescript in production code.
But there is a problem with a cache. If you will add:

```js
cache: {
        name: 'test',
        type: 'filesystem',
        buildDependencies: {
          config: [__filename]
        }
      },
```
to your webpack config, the first test will be ok, but the second will fail. The problem is, that plugin won't be executed, if webpack uses a code from cache. And I do not know, how to fix it(

Of course, I can use in memory cache, but the first build will take much time.

By the way, in memory cache will break the code too. If I change a transport — I will see an error:
```
logServerUncaughtException error:  Error: The worker thread exited
    at Worker.onWorkerExit (/Users/a.malko/Work/react-ssr-template/build/main.js:95787:32)
    at Worker.emit (node:events:390:28)
    at Worker.[kOnExit] (node:internal/worker:278:10)
    at Worker.<computed>.onexit (node:internal/worker:198:20)
/Users/a.malko/Work/react-ssr-template/build/main.js:95821
      throw new Error('the worker has exited')
      ^

Error: the worker has exited
    at ThreadStream.write (/Users/a.malko/Work/react-ssr-template/build/main.js:95821:13)
    at Pino.write (/Users/a.malko/Work/react-ssr-template/build/main.js:99370:10)
    at Pino.LOG [as error] (/Users/a.malko/Work/react-ssr-template/build/main.js:99677:21)
    at logServerUncaughtException (/Users/a.malko/Work/react-ssr-template/build/main.js:10882:66)
    at process.<anonymous> (/Users/a.malko/Work/react-ssr-template/build/main.js:101485:133)
    at process.emit (node:events:390:28)
    at process._fatalException (node:internal/process/execution:170:25)
```

**Comment by artem-malko** [comment]
By the way, I can not understand, why it is not possible to use just [BannerPlugin](https://webpack.js.org/plugins/banner-plugin/)? I've tried to use it, but I have an error:
```
the worker is exited
```

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue?

**Comment by artem-malko** [comment]
@mcollina the pull request with the bug, right?

**Comment by artem-malko** [comment]
And it's done)

**Comment by mcollina** [comment]
With the fix too!

**Comment by artem-malko** [comment]
Sorry, I do not know, how to fix it(
